lib/init.js, package-lock.json, package.json, test/init.test.js
Use new tvm npm name: `aio-lib-tvm`
=> rename tvm client dependency

doc/api.md, lib/StateStore.js, lib/StateStoreError.js, lib/impl/CosmosStateStore.js, lib/init.js, lib/types.jsdoc.js, package-lock.json, package.json, test/StateStore.test.js, test/impl/CosmosStateStore.test.js, test/init.test.js, test/jest.setup.js
Integrate with aio-lib-core-errors
=> ACNA-440 - integrate with aio-lib-core-errors

lib/StateStoreError.js, lib/init.js, package-lock.json, package.json, test/init.test.js
update aio-lib-core-errors 2.0 and aio-lib-core-tvm (renamed)
=> update aio-lib-core-errors and aio-lib-core-tvm

doc/api.md, lib/StateStore.js, lib/impl/CosmosStateStore.js, test/impl/CosmosStateStore.test.js
current behavior: if delete is called on a non existing state key, an ERROR_INTERNAL is thrown.
new behavior: return null
=> fix delete and change return value to null if key does not exist

README.md, lib/StateStore.js, lib/StateStoreError.js, lib/impl/CosmosStateStore.js, lib/init.js, package-lock.json, package.json, test/StateStore.test.js, test/impl/CosmosStateStore.test.js, test/init.test.js, test/jest.setup.js
=> ACNA-439 - Integrate with core logging SDK

lib/StateStoreError.js, lib/init.js, test/init.test.js
=> Fix tvm error handling

lib/StateStore.js, lib/StateStoreError.js, lib/impl/CosmosStateStore.js, lib/init.js, package.json
fix logger lib breaking change
=> Fix logger update

README.md, doc/api.md, e2e/e2e.js, lib/init.js
=> fix reading OW env var

README.md
=> troubleshoot webpack errors

package.json
=> chore(package): update @azure/cosmos to version 3.5.0

README.md
=> ACNA-601 - Document consistency model

index.js
=> ACNA-561 - Fixing autocompletion

package.json
=> chore(package): update eslint-plugin-jsdoc to version 20.3.1

jsconfig.json, package.json, types.d.ts
Trying to improve autocomplete in VS Code.
Better developer experience.
1. npm test
2. vs code autocomplete
=> fix: generate typings from jsdoc

README.md
=> update namespace restriction

doc/api.md, lib/StateStore.js, lib/impl/CosmosStateStore.js, package.json, types.d.ts
fix for #52 
+ hides protected methods
=> fix autocompletion and protected methods

lib/StateStoreError.js, lib/impl/CosmosStateStore.js, test/impl/CosmosStateStore.test.js, test/jest.setup.js
=> Fix firewall error message

README.md
=> Add pre-req for the BYO cosmos DB account

lib/StateStore.js, lib/impl/CosmosStateStore.js, package.json
=> update deprecated @hapi/joi to joi

README.md
Fix the code sample in the README
n/a
=> #trivial - fix minor typo in README

lib/impl/CosmosStateStore.js, lib/init.js, test/impl/CosmosStateStore.test.js
=> Reuse CosmosClient instance to save on Metadata RUs

doc/api.md, lib/StateStoreError.js, types.d.ts
=> fix: add StateLibError type in docs

package.json
See https://github.com/Azure/azure-sdk-for-js/issues/22968
npm test
=> fix: pin @azure/cosmos to 3.16.4 due to issue with 3.17.0

package.json
See https://github.com/Azure/azure-sdk-for-js/issues/22968
- npm test
- repro steps from the Azure issue above w/ v3.17.1
=> fix: update pinned @azure/cosmos version (Microsoft bug was fixed)

doc/api.md, lib/AdobeState.js, types.d.ts
=> chore: fix stats() return type

e2e/.env.example, e2e/e2e.md, lib/AdobeState.js, lib/constants.js, test/AdobeState.test.js, test/utils.test.js
This PR proposes a refactoring of the environment configuration to expose a single environment variable `AIO_STATE_ENDPOINT=<protocol>://<customhost>` which allows for setting both the protocol and the host. 
- State lib does not need to check if the host is local to determine the protocol.
- This way, when using a custom host, the environment and the region don't need to be set, as they are embedded in the host itself. This will avoid confusion in cases where the host targets a non-prod/non-stage environment or when the region is not one of `amer`, `apac`, `emea` (thinking of e2e testing failover region such as va7)
I may have missed some internals so the PR is up for debate.
=> chore!: simplify environment configuration

README.md
Relates to https://github.com/AdobeDocs/app-builder/pull/334/files
=> chore: move documentation to the AppBuilder repo

README.md
=> chore: readme for 3.x do not cache state instance

lib/AdobeState.js, lib/constants.js, test/AdobeState.test.js
see https://git.corp.adobe.com/CNA/adp-storage-state/pull/58
=> chore!: remove api version from path

doc/api.md, lib/AdobeState.js, package.json, types.d.ts
we need a release for the types after merge.
=> fix: types api doc and types, hook to run generation on commit

e2e/e2e.js
=> fix: update unauthorized e2e test for latest breaking change
